//test-data.js

export function createTestSnapshot() {

  return {
    units: [

      {
        id:"Eno1",
        name:"左軍１",
        team:1,
        role:"attack",
        hp:30,
        atk:8,
        df:3,
        speed:10,
        x:0,
        y:0,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D06.webp",
        skills:[]
      },

      {
        id:"Eno2",
        name:"左軍２",
        team:1,
        role:"defense",
        hp:40,
        atk:6,
        df:6,
        speed:7,
        x:1,
        y:2,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D08.webp",
        skills:[]
      },

      {
        id:"Eno3",
        name:"左軍３",
        team:1,
        role:"heal",
        hp:28,
        atk:5,
        df:3,
        speed:9,
        x:2,
        y:4,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D13.webp",
        skills:[]
      },

      {
        id:"Eno4",
        name:"左軍４",
        team:1,
        role:"speed",
        hp:25,
        atk:7,
        df:2,
        speed:12,
        x:3,
        y:1,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D21.webp",
        skills:[]
      },

      {
        id:"Eno5",
        name:"左軍５",
        team:1,
        role:"technical",
        hp:32,
        atk:7,
        df:4,
        speed:8,
        x:3,
        y:3,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D11.webp",
        skills:[]
      },

      {
        id:"Nno1",
        name:"右軍１",
        team:2,
        role:"attack",
        hp:30,
        atk:8,
        df:3,
        speed:9,
        x:9,
        y:0,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D07.webp",
        skills:[]
      },

      {
        id:"Nno2",
        name:"右軍２",
        team:2,
        role:"defense",
        hp:42,
        atk:6,
        df:7,
        speed:6,
        x:8,
        y:2,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D10.webp",
        skills:[]
      },

      {
        id:"Nno3",
        name:"右軍３",
        team:2,
        role:"heal",
        hp:26,
        atk:5,
        df:3,
        speed:10,
        x:7,
        y:4,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D05.webp",
        skills:[]
      },

      {
        id:"Nno4",
        name:"右軍４",
        team:2,
        role:"speed",
        hp:24,
        atk:7,
        df:2,
        speed:12,
        x:6,
        y:1,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D03.webp",
        skills:[]
      },

      {
        id:"Nno5",
        name:"右軍５",
        team:2,
        role:"technical",
        hp:31,
        atk:7,
        df:4,
        speed:8,
        x:6,
        y:3,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D04.webp",
        skills:[]
      }

    ]
  };
}
