//test-data.js

export function createTestSnapshot() {

  return {
    units: [

      {
        id:"Eno1",
        name:"左軍アタック",
        team:1,
        role:"attack",
        hp:30,
        mhp:30,
        atk:8,
        df:3,
        speed:10,
        x:2,
        y:4,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D06.webp",
        skills:["buff_self_if_alone",
               "attack_nearest"]
      },

      {
        id:"Eno2",
        name:"左軍ディフェンス",
        team:1,
        role:"defense",
        hp:40,
        mhp:40,
        atk:6,
        df:6,
        speed:7,
        x:1,
        y:2,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D08.webp",
        skills:["buff_df50_self",
                "attack_front_knockback"]
      },

      {
        id:"Eno3",
        name:"左軍ヒール",
        team:1,
        role:"heal",
        hp:28,
        mhp:28,
        atk:5,
        df:3,
        speed:9,
        x:0,
        y:2,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D13.webp",
        skills:["heal_cross2"]
      },

      {
        id:"Eno4",
        name:"左軍スピード",
        team:1,
        role:"speed",
        hp:25,
        mhp:25,
        atk:7,
        df:2,
        speed:12,
        x:2,
        y:1,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D21.webp",
        skills:["buff_self_if_alone",
               "attack_front1"]
      },

      {
        id:"Eno5",
        name:"左軍テクニカル",
        team:1,
        role:"technical",
        hp:32,
        mhp:32,
        atk:7,
        df:4,
        speed:8,
        x:2,
        y:5,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D11.webp",
        skills:["attack_around2_all"]
      },

      {
        id:"Eno6",
        name:"左軍サポート",
        team:1,
        role:"support",
        hp:32,
        mhp:32,
        atk:7,
        df:4,
        speed:8,
        x:2,
        y:5,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D11.webp",
        skills:["pull_farthest_enemy",
               "attack_random_falloff"]
      },
      {
        id:"Nno1",
        name:"右軍アタック",
        team:2,
        role:"attack",
        hp:30,
        mhp:30,
        atk:8,
        df:3,
        speed:9,
        x:9,
        y:0,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D07.webp",
        skills:["buff_self_if_alone",
               "attack_nearest"]
      },

      {
        id:"Nno2",
        name:"右軍ディフェンス",
        team:2,
        role:"defense",
        hp:42,
        mhp:42,
        atk:6,
        df:7,
        speed:6,
        x:8,
        y:2,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D10.webp",
        skills:["buff_df50_self",
                "attack_front_knockback"]
      },

      {
        id:"Nno3",
        name:"右軍ヒール",
        team:2,
        role:"heal",
        hp:26,
        mhp:26,
        atk:5,
        df:3,
        speed:10,
        x:9,
        y:4,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D05.webp",
        skills:["heal_cross2"]
      },

      {
        id:"Nno4",
        name:"右軍スピード",
        team:2,
        role:"speed",
        hp:24,
        mhp:24,
        atk:7,
        df:2,
        speed:12,
        x:6,
        y:1,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D03.webp",
        skills:["buff_self_if_alone",
               "attack_front1"]
      },

      {
        id:"Nno5",
        name:"右軍テクニカル",
        team:2,
        role:"technical",
        hp:31,
        mhp:31,
        atk:7,
        df:4,
        speed:8,
        x:6,
        y:3,
        facing:"W",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D04.webp",
        skills:["attack_around2_all"]
      },
      {
        id:"Nno6",
        name:"右軍サポート",
        team:2,
        role:"support",
        hp:32,
        mhp:32,
        atk:7,
        df:4,
        speed:8,
        x:2,
        y:5,
        facing:"E",
        icon:"https://www.rabbithutch.site/usagoya/picture.php?user=1217karen&file=D11.webp",
        skills:["pull_farthest_enemy",
               "attack_random_falloff"]
      }
    ]
  };
}
